# Generated by Django 3.2.1 on 2022-01-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uuid',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
