# Generated by Django 3.2.1 on 2022-01-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20220112_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='questuin_id',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choices',
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='quiz_app.Choice'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='quiz_uuid',
            field=models.CharField(max_length=20),
        ),
    ]
