# Generated by Django 3.2.1 on 2022-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20220115_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questuin_id',
            new_name='questuion_id',
        ),
    ]
