# Generated by Django 3.2.1 on 2022-01-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_rename_questuin_id_answer_questuion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questuion_id',
            new_name='question_id',
        ),
    ]
